Neos:
  Neos:
    modules:
      administration:
        submodules:
          flownativeCacheManagementCaches:
            label: 'Caches'
            icon: 'fas fa-bolt'
            controller: 'Flownative\Neos\CacheManagement\Controller\Module\Administration\CachesController'
            description: 'Provides administration tools for maintaining caches.'
            privilegeTarget: 'Flownative.Neos.CacheManagement:Backend.Module.Administration.Caches'
Flownative:
  Neos:
    CacheManagement:
      ui:
        showCacheHint: true
        hideCachesWithoutLabel: false
      caches:
        Neos_Fusion_Content:
          label: 'Neos Content'
          description: 'Caches the rendering of Neos content elements.'
        Flow_Mvc_Routing_Route:
          label: 'Routes (Matching)'
          description: 'Caches the matching of routes to controllers and actions.'
        Flow_Mvc_Routing_Resolve:
          label: 'Routes (Resolving)'
          description: 'Caches the resolving of routes to URIs.'
